name: CI

on:
  push:
    branches: ["master"]

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-latest }
          - { name: Linux, os: ubuntu-latest }
          - { name: macOS, os: macos-latest }
        build_type:
          - debug
          - release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SFML (macOS)
        if: runner.os == 'macOS'
        run: brew install sfml

      - name: Install SFML Dependencies (Linux/FreeType Fix)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev libxi-dev libfreetype6-dev cmake \
            libxrandr-dev libxcursor-dev
          
      - name: Install SFML (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          $sfml_url = "https://www.sfml-dev.org/files/SFML-3.0.2-windows-vc17-64-bit.zip"
          $sfml_zip = "sfml.zip"
          $install_dir = "C:\sfml-install"
         
          Write-Host "Downloading SFML from $sfml_url"
          Invoke-WebRequest -Uri $sfml_url -OutFile $sfml_zip
         
          New-Item -ItemType Directory -Force -Path $install_dir
          Expand-Archive -Path $sfml_zip -DestinationPath $install_dir
          Write-Host "SFML installed to $install_dir"

      - name: Build
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cmake -B build -S . `
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
              -DSFML_DIR=C:/sfml-install/SFML-3.0.2-windows-vs2022-64-bit/lib/cmake/SFML
          else
            cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          fi
          cmake --build build --config ${{ matrix.build_type }}
