name: CI

on:
  push:
    branches: ["master"]

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-latest }
          - { name: Linux, os: ubuntu-latest }
          - { name: macOS, os: macos-latest }
        build_type:
          - debug
          - release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup vcpkg
        uses: vcpkg-tool/setup-vcpkg@v1
        id: vcpkg_setup

      - name: Install SFML via vcpkg
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            vcpkg install sfml:x64-windows
          elif [ "${{ runner.os }}" == "Linux" ]; then
            vcpkg install sfml:x64-linux
          elif [ "${{ runner.os }}" == "macOS" ]; then
            vcpkg install sfml:x64-osx
          fi

      - name: Build
        run: |
          cmake -B build -S . `
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg_setup.outputs.vcpkg-root }}/scripts/buildsystems/vcpkg.cmake `
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          cmake --build build --config ${{ matrix.build_type }}
