name: CI

on:
  push:
    branches: ["master"]

  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows, os: windows-latest }
          - { name: Linux, os: ubuntu-latest }
          - { name: macOS, os: macos-latest }
        build_type:
          - debug
          - release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install FreeType (Linux workaround)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libfreetype6-dev

      - name: Install missing X11 deps (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libxi-dev

      - name: Install SFML 3.0.2
        uses: oprypin/install-sfml@v1
        with:
          sfml: "3.0.2"

      - name: Build
        run: ./build.sh ${{ matrix.build_type }}
